# lang.py – Zweisprachige Texte DE / EN
TEXTS = {
    "de": {
        "app_title": "Zucker Bubi – Blutzucker Manager",
        "dashboard": "Dashboard", "eingabe": "Eingabe", "uebersicht": "Übersicht",
        "bericht": "Arztbericht", "einstellungen": "Einstellungen",
        "verbindung": "Verbindung",
        "hilfe": "Hilfe", "ueber": "Über",
        "btn_sync": "⟳  Gerät synchronisieren", "btn_add": "+ Wert hinzufügen",
        "btn_save": "Speichern", "btn_cancel": "Abbrechen", "btn_delete": "🗑 Löschen",
        "btn_pdf": "📄 PDF erstellen", "btn_print": "🖨 Drucken",
        "lbl_date": "Datum", "lbl_time": "Uhrzeit", "lbl_value": "Wert",
        "lbl_unit": "Einheit", "lbl_note": "Notiz", "lbl_type": "Messtyp",
        "type_nuchtern": "Nüchtern", "type_vor_essen": "Vor dem Essen",
        "type_nach_essen": "Nach dem Essen", "type_sonstige": "Sonstige",
        "today_avg": "Tages-Ø", "today_count": "Messungen heute",
        "week_avg": "7-Tage-Ø", "month_avg": "30-Tage-Ø",
        "hba1c_est": "HbA1c (est.)", "tir": "Zeit im Ziel",
        "last_value": "Letzter Wert", "last_7days": "Letzte 7 Tage",
        "patient_name": "Patientenname", "patient_dob": "Geburtsdatum",
        "patient_id": "Patienten-ID", "doctor_name": "Arztname",
        "doctor_address": "Praxisadresse", "report_period": "Berichtszeitraum",
        "days_7": "7 Tage", "days_14": "14 Tage", "days_30": "30 Tage", "days_90": "90 Tage",
        "bt_scanning": "Suche nach Bluetooth-Geräten …",
        "bt_found": "Gerät gefunden – synchronisiere …",
        "bt_connected": "Synchronisierung abgeschlossen",
        "bt_failed": "Verbindung fehlgeschlagen",
        "bt_no_device": "Kein kompatibles Gerät gefunden",
        "bt_no_bleak": "bleak nicht installiert – manuelle Eingabe nutzen",
        "status_normal": "Normal", "status_high": "Erhöht",
        "status_low": "Niedrig", "status_very_high": "Sehr hoch",
        "status_very_low": "Sehr niedrig",
        "no_data": "Keine Daten vorhanden",
        "saved": "✓ Gespeichert", "error": "Fehler", "del_confirm": "Wirklich löschen?",
        "language": "Sprache", "unit_lbl": "Einheit", "target_range": "Zielbereich",
        "mgdl": "mg/dL", "mmol": "mmol/L",
        "min": "Min", "max": "Max", "avg": "Ø", "std": "Stabw",
        "report_title": "Blutzucker-Bericht",
        "report_stats": "Statistik", "report_chart": "Wochenverlauf",
        "report_table": "Messwerte", "report_tir": "Zeit im Zielbereich",
        "disclaimer": "Dieses Programm dient nur zur persönlichen Dokumentation und ersetzt keine ärztliche Beratung.",
        "third_party": "Drittanbieter: matplotlib, reportlab, bleak, customtkinter (MIT/LGPL/Apache)",
        "help_intro": "Willkommen bei Zucker Bubi!\n\nDieses Programm hilft Ihnen, Ihre Blutzuckerwerte zu erfassen, auszuwerten und für Ihren Arzt aufzubereiten.",
        "unit_hint": "1 mmol/L ≈ 18 mg/dL",
        "note_placeholder": "Optionale Notiz …",
        "select_period": "Zeitraum wählen",
        "create_report": "Bericht erstellen",
        "pdf_saved": "PDF gespeichert",
        "pdf_path": "Gespeichert unter",
        "today": "Heute",
        "value_invalid": "Ungültiger Wert. Bitte Zahl eingeben (z.B. 5,4 oder 97).",
    },
    "en": {
        "app_title": "Zucker Bubi – Blood Sugar Manager",
        "dashboard": "Dashboard", "eingabe": "Entry", "uebersicht": "Overview",
        "bericht": "Doctor Report", "einstellungen": "Settings",
        "verbindung": "Connection",
        "hilfe": "Help", "ueber": "About",
        "btn_sync": "⟳  Sync Device", "btn_add": "+ Add Value",
        "btn_save": "Save", "btn_cancel": "Cancel", "btn_delete": "🗑 Delete",
        "btn_pdf": "📄 Create PDF", "btn_print": "🖨 Print",
        "lbl_date": "Date", "lbl_time": "Time", "lbl_value": "Value",
        "lbl_unit": "Unit", "lbl_note": "Note", "lbl_type": "Type",
        "type_nuchtern": "Fasting", "type_vor_essen": "Before Meal",
        "type_nach_essen": "After Meal", "type_sonstige": "Other",
        "today_avg": "Daily Avg", "today_count": "Today's Readings",
        "week_avg": "7-Day Avg", "month_avg": "30-Day Avg",
        "hba1c_est": "HbA1c (est.)", "tir": "Time in Range",
        "last_value": "Last Value", "last_7days": "Last 7 Days",
        "patient_name": "Patient Name", "patient_dob": "Date of Birth",
        "patient_id": "Patient ID", "doctor_name": "Doctor Name",
        "doctor_address": "Practice Address", "report_period": "Report Period",
        "days_7": "7 Days", "days_14": "14 Days", "days_30": "30 Days", "days_90": "90 Days",
        "bt_scanning": "Scanning for Bluetooth devices …",
        "bt_found": "Device found – syncing …",
        "bt_connected": "Sync completed",
        "bt_failed": "Connection failed",
        "bt_no_device": "No compatible device found",
        "bt_no_bleak": "bleak not installed – use manual entry",
        "status_normal": "Normal", "status_high": "Elevated",
        "status_low": "Low", "status_very_high": "Very high",
        "status_very_low": "Very low",
        "no_data": "No data available",
        "saved": "✓ Saved", "error": "Error", "del_confirm": "Really delete?",
        "language": "Language", "unit_lbl": "Unit", "target_range": "Target Range",
        "mgdl": "mg/dL", "mmol": "mmol/L",
        "min": "Min", "max": "Max", "avg": "Avg", "std": "StDev",
        "report_title": "Blood Sugar Report",
        "report_stats": "Statistics", "report_chart": "Weekly Trend",
        "report_table": "Readings", "report_tir": "Time in Range",
        "disclaimer": "This program is for personal documentation only and does not replace medical advice.",
        "third_party": "Third-party: matplotlib, reportlab, bleak, customtkinter (MIT/LGPL/Apache)",
        "help_intro": "Welcome to Zucker Bubi!\n\nThis application helps you record, analyze and present your blood glucose readings to your doctor.",
        "unit_hint": "1 mmol/L ≈ 18 mg/dL",
        "note_placeholder": "Optional note …",
        "select_period": "Select period",
        "create_report": "Create report",
        "pdf_saved": "PDF saved",
        "pdf_path": "Saved to",
        "today": "Today",
        "value_invalid": "Invalid value. Please enter a number (e.g. 5.4 or 97).",
    }
}

_lang = ["de"]

def set_lang(code: str):
    _lang[0] = code if code in TEXTS else "de"

def t(key: str) -> str:
    return TEXTS[_lang[0]].get(key, TEXTS["de"].get(key, key))

def get_lang() -> str:
    return _lang[0]
